### ISSUE TITLE
Add support for file path matching

### ISSUE THREAD

**Issue by vtron** [Applelo/unplugin-inject-preload#3]
I can only get this to work by providing regex for file names. 

It would be better if I could specify the file path of the entry so I can preload based on folders and not rely on prefixing files.

 I would like to do something like this:

```
.*\/wallpaper\/.*\.jpg
```

to match 
```src/assets/wallpaper/*```

Am I missing something, or is this supported? I am using Vite.

**Comment by Applelo** [comment]
Hi, thanks for your issue, I will check if I can make this work.

**Comment by Applelo** [comment]
So I have check and ViteJS return only the name of the entryFile. I have no way to get the fullpath :/ I keep this issue in mind if I found something, I will try to implement it.
