### ISSUE TITLE
Only supports Vite 'build'

### ISSUE THREAD

**Issue by vtron** [Applelo/unplugin-inject-preload#4]
Support for the "serve" target would be helpful when developing. 

Right now it looks like this plugin is restricted to "build" only, which means it will not inject preloads while running 'dev' ('serve' target).

If this is intentional, it may be helpful to note in the documentation.

**Comment by Applelo** [comment]
Hi, this feature is not supported with vite because it relies on rollup only on build. I have already mention this in the previous plugin https://github.com/Applelo/vite-plugin-inject-preload/issues/15 and this is already mention in the readme. Maybe I need to put it in bold 😛
