### ISSUE TITLE
Redundant `/` prefixed the output path if `base` of vite config is relative, such as `./`

### ISSUE THREAD

**Issue by kiddliu** [Applelo/unplugin-inject-preload#9]
After upgraded from `vite-plugin-inject-preload`, the output path of each preloaded file got a redundant `/` if the `base` of vite config is relative.

_Output_
![output](https://github.com/Applelo/unplugin-inject-preload/assets/3058252/e9e026b9-69a2-4b59-b8c2-14708de3ff14)

_vite.config.ts_
![vite.config.ts](https://github.com/Applelo/unplugin-inject-preload/assets/3058252/0eaac8a3-7e6e-4522-bf41-570f1c3fdd00)

Digging into the source https://github.com/Applelo/unplugin-inject-preload/blob/main/src/helper/getTagsAttributes.ts#L12
```
function pathJoin(...strs: string[]) {
  let path = ''
  for (let index = 0; index < strs.length; index++) {
    const str = strs[index]
    const previousStr = index ? strs[index - 1] : ''

    if (str && !str.startsWith('/') && !previousStr.endsWith('/'))   <--- don't understand what scenario it deals with, but the problem is here
      path += `/${str}`
    else
      path += str
  }

  return path
}
```

And since it's a regression bug, it'd be nice to have a fix.

**Comment by Applelo** [comment]
A fix is deployed, feel free to reopen the issue if this is not fixed for you.

**Comment by kiddliu** [comment]
Thank you for the quick action, however `path.resolve` would give an absolute path where the build process actual happens, e.g. in a k8s pod and that's not what's expected with a relative `base`.

Strange that as the author of the issue, I didn't see the _reopen_ button...strange...

**Comment by Applelo** [comment]
Hi, my bad, a `path.join` should do the trick I think 🤔 I don't have proper test to reproduce this issue. If you have a reproduction on https://stackblitz.com/ it could help me to resolve this bug.

**Comment by kiddliu** [comment]
Check this https://stackblitz.com/edit/vitejs-vite-fks4es?file=dist%2Findex.html

**Comment by kiddliu** [comment]
The stackblitz is updated, and it looks good to me! Thank you!
